apiVersion: v1
kind: Namespace
metadata:
  name: k8s-trigger
  labels:
    name: k8s-trigger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-trigger
  namespace: k8s-trigger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-trigger-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: k8s-trigger
  namespace: k8s-trigger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-trigger
  namespace: k8s-trigger
  labels:
    app: k8s_trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s_trigger
  template:
    metadata:
      labels:
        app: k8s_trigger
    spec:
      serviceAccountName: k8s-trigger
      containers:
      - name: trigger
        image: annat/k8s-trigger
        env:
          - name: secret
            value: "6FGS959U9epLIJ6crvu4l2TsdpD4Ozyz2M7JEravear"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-trigger-svc
  namespace: k8s-trigger
  labels:
    app: k8s_trigger
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: k8s_trigger
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80